### ISSUE TITLE
Add helpers to core

### ISSUE THREAD

**Issue by jamesdbaker** [annot8/annot8-archived#8]
Add helpers to the core such as 'AnnotationStore.getContent()' since it's very painful to pass around Item, Content, etc.

**Comment by chrisflatley** [comment]
- [x] AnnotationStore.getContent
- [x] GroupStore.getItem
- [ ] Annotation.getContent
- [x] Content.getItem
- [ ] Group.getItem

**Comment by chrisflatley** [comment]
Not adding for group and annotation
